development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:005b6011af87d9fa750b7e2b88ff89ba@tetra.redistogo.com:9347/
  channel_prefix: message_me_production
